### ISSUE TITLE
How to extract features for the DBMSs apart from PostgreSQL?

### ISSUE THREAD

**Issue by bajinsheng** [zhaoyue-ntu/QueryFormer#1]
Hi, I am quite interested in your work and have a question about feature extraction.

From the paper, I saw that the raw physical query plans have to be translated into Node features as the input for QueryFormer. If I understand correctly, this is the code to do the feature extraction: https://github.com/zhaoyue-ntu/QueryFormer/blob/4890f1d0a41dbf76b68c23991c7ff86504b780c0/model/database_util.py#L71.

I am wondering if is it customized for PostgreSQL. How can I try this work for other DBMSs?

By the way, is it correct to state the overall workflow: raw physical query plans -> extract features -> train it to super nodes as the vector inputs for ML tasks -> ML prediction?

**Comment by zhaoyue-ntu** [comment]
Hi Jinsheng,

is it customized for PostgreSQL. How can I try this work for other DBMSs?

Yes, the version is customized for Postgres, because different systems have different query plan format. You may need to edit the feature extraction part (predicate, operator, etc.,) according to the format of the query plans of your DBMS. The collection of samples/histograms may be different too. If your DBMS does not already have samples/hists, the easiest way (i think) is to export the data stored in DBMS outside and use tools like pandas.

is it correct to state the overall workflow: raw physical query plans -> extract features -> train it to super nodes as the vector inputs for ML tasks -> ML prediction?

Yes you are exactly right.

Thank you for your interest in the paper. Let me know if any other questions.

Regards,
Zhao Yue

________________________________
From: Jinsheng Ba ***@***.***>
Sent: Wednesday, March 29, 2023 10:54 AM
To: zhaoyue-ntu/QueryFormer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zhaoyue-ntu/QueryFormer] How to extract features for the DBMSs apart from PostgreSQL? (Issue #1)


Hi, I am quite interested in your work and have a question about feature extraction.

From the paper, I saw that the raw physical query plans have to be translated into Node features as the input for QueryFormer. If I understand correctly, this is the code to do the feature extraction: https://github.com/zhaoyue-ntu/QueryFormer/blob/4890f1d0a41dbf76b68c23991c7ff86504b780c0/model/database_util.py#L71.

I am wondering if is it customized for PostgreSQL. How can I try this work for other DBMSs?

By the way, is it correct to state the overall workflow: raw physical query plans -> extract features -> train it to super nodes as the vector inputs for ML tasks -> ML prediction?

**Comment by bajinsheng** [comment]
I see. Thanks for your prompt reply!
